---
title: "Fiche 2 : Comprendre les types de produit de recherche"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

------------------------------------------------------------------------

## Galerie d'exemple des produits de recherche proposés par DMP OPIDoR

|                              |                                                                                                                                                                                                                                                           |                                                                                                                                                                                                                                                   |
|------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Type de produit de recherche | Définition                                                                                                                                                                                                                                                | Exemple de PGD public                                                                                                                                                                                                                             |
| **Audiovisuel**              | Série de représentations visuelles donnant une impression de mouvement lorsqu'elles sont présentées successivement. Peut inclure ou ne pas inclure du son.                                                                                                | [Projet SituLearn ](https://dmp.opidor.fr/plans/9357/export.pdf): Captation image et vidéo des expérimentations                                                                                                                                   |
| **Collection**               | Agrégation de ressources pouvant comprendre des collections d'un même type de ressource ainsi que des collections de type de ressources différentes. Une collection est décrite comme un groupe ; ses parties peuvent également être décrites séparément. | [Projet Bridge Research through Interoperable Data Governance and Environments ](https://dmp.opidor.fr/plans/5954/export.pdf): Corpus de textes sur la gouvernance des données, Grilles d'analyse, éléments bibliographiques, rapport de synthèse |
| **Jeu de données**           | Ensemble cohérent de données produites dans le cadre d'un même projet, sur un même objet d'étude et/ou recueillies sur un même lieu.                                                                                                                      | [Projet "Water and Ice-related thermo-mechanical processes in the fractures of Steep alpine bedrock Permafrost"](https://dmp.opidor.fr/plans/7067/export.pdf) : Statistical analysis of modeled rockwall tempertaure at 209 rockfalls             |
| **Image**                    | Représentation visuelle autre que du texte.                                                                                                                                                                                                               | [Projet "E-NdP"](https://dmp.opidor.fr/plans/10339/export.pdf) : Numérisation de manuscrits                                                                                                                                                       |
| **Ressource interactive**    | Ressource nécessitant une interaction de l'utilisateur pour être comprise, exécutée ou expérimentée.                                                                                                                                                      | [Projet "Hoppe Droit - Hypothèses d'Observation des Productions Pédagogiques Editées en Droit"](https://dmp.opidor.fr/plans/3827/export.pdf) : Interface de visualisation de Hoppe Droit                                                                                                          [Projet "PGD HyperOtlet"](https://dmp.opidor.fr/plans/4205/export.pdf) : CMS <http://hyperotlet-collections.huma-num.fr/>                                                                                                                          |
| **Modèle**                   | Modèle abstrait, conceptuel, graphique, mathématique ou de visualisation représentant des objets, des phénomènes ou des processus physiques empiriques.                                                                                                   | [Projet "E-NdP", Modèles de transcription automatique de l'écriture manuscrite ](https://dmp.opidor.fr/plans/10339/export.pdf): Modèles de transcription automatique de l'écriture manuscrite                                                     |
| **Objet physique**           | Objet ou substance inanimé en trois dimensions.                                                                                                                                                                                                           | [Projet "Les artothèques publiques françaises et leurs collections 1982-2022 (public)"](https://dmp.opidor.fr/plans/13446/export.pdf) : Baluchons sensoriels                                                                                      |
| **Service**                  | Système organisé d'appareils, de dispositifs, de personnel, etc., pour fournir certaines fonctions requises par les utilisateurs finaux.                                                                                                                  | [Projet "PGD HyperOtlet"](https://dmp.opidor.fr/plans/4205/export.pdf) : Sharedocs du projet HyperOtlet (Hébergé par la TGIR HumNum)                                                                                                              |
| **Logiciel**                 | Programme informatique sous forme de code source (texte) ou sous forme compilée. Utiliser ce type pour tous les composants logiciels venant en appui à la recherche académique.                                                                           | [Projet Bridge Research through Interoperable Data Governance and Environments](https://dmp.opidor.fr/plans/5954/export.pdf) : Widget d'autocomplétion pour améliorer les métadonnées                                                          [Projet "ERC PTEROSOR"](https://dmp.opidor.fr/plans/6397/export.pdf) : Quantum Package                                                                                                                                                             |
| **Son**                      | Ressource principalement destinée à être entendue.                                                                                                                                                                                                        | [Projet ATLATS](https://dmp.opidor.fr/plans/3354/export.pdf), données d'enquête format audio                                                                                                                                                      |
| **Texte**                    | Ressource composée principalement de mots à lire.                                                                                                                                                                                                         | [Projet Bridge Research through Interoperable Data Governance and Environments](https://dmp.opidor.fr/plans/5954/export.pdf) : Critères et guide pratiques pour étudier le degré FAIR des entrepôts et application aux cas d'études               |
| **Workflow**                 | Série structurée d'étapes pouvant être exécutées pour produire un résultat final, offrant aux utilisateurs un moyen de mettre à oeuvre leur travail de manière plus reproductible.                                                                        | [Projet SituLearn ](https://dmp.opidor.fr/plans/9357/export.pdf): traces d'usage des applications proposées                                                                                                                                       |
| **Autre**                    | Tout autre type de produit de recherche.                                                                                                                                                                                                                  |                                                                                                                                                                                                                                                   |

**Merci aux contributeurs des PGD publics sur DMP OPIDoR d'avoir partagé leur PGD librement.**
