---
title: "Fiche 16 - Choisir un type d'entrepôt"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

------------------------------------------------------------------------

Si votre institution ne recommande par d'entrepôt prédéfini, vous pouvez consulter les critères de sélection d'un entrepôt de données ainsi que notre galerie d'exemples.

------------------------------------------------------------------------

## Critères pour choisir un entrepôt :

Si le choix de l'entrepôt vous revient, voici une liste de critères pour vous aider :

-   privilégier un entrepôt disciplinaire

-   choisir un entrepôt en fonction des types de données acceptés

-   vérifier la qualité des métadonnées requise

-   vérifier si l'entrepôt envisagé est certifié

-   vérifier si l'entrepôt envisagé est labellisé "entrepôt de confiance"

-   vérifier la pérennité proposée par l'entrepôt

-   voir si le dépôt de données dans l'entrepôt envisagé génère un identifiant pérenne

-   vérifier si l'entrepôt envisagé permet la gestion des versions si tel est votre besoin.

------------------------------------------------------------------------

## Galerie d'exemples d'entrepôts disciplinaires et généralistes

Il est conseillé de privilégier le dépôt de vos données dans un **entrepôt disciplinaire**. S'il n'en existe pas dans votre domaine, vous pouvez opter pour un **entrepôt généraliste**.

Voici quelques exemples :

#### Zenodo (pluridisciplinaire)

Entrepôt généraliste recommandé par la Commission européenne [(voir le site)](https://zenodo.org)

------------------------------------------------------------------------

#### Dryad (pluridisciplinaire)

Entrepôt en Sciences de la Vie, Agronomie, Géosciences, Anthropologie et Sciences comportementales [(voir le site)](https://datadryad.org/stash)

------------------------------------------------------------------------

#### Datasuds (institutionnel IRD)

L'entrepôt de données DataSuds propose aux scientifiques de l'IRD et à leurs partenaires un service pour diffuser, préserver et valoriser leurs données de recherche en facilitant leur identification et leur citation.

------------------------------------------------------------------------

#### Recherche data gouv (national)

Une plateforme nationale fédérée des données de la recherche([voir le site](https://recherche.data.gouv.fr/fr))

il assure la souveraineté française sur les données, est conforme aux droits français et communautaire, garantit la pérennité et l'indexation des données stockées, suivant les principes FAIR. C'est l'entrepôt de choix quand aucun entrepôt disciplinaire n'existe.

Source : *Partager les données liées aux publications scientifiques -- Guide pour les chercheurs*. (2022). from <https://www.ouvrirlascience.fr/partager-les-donnees-liees-aux-publications-scientifiques-guide-pour-les-chercheurs>​

------------------------------------------------------------------------

**Astuce** **: On peut faire appel à son service d'appui à la recherche pour bien choisir son entrepôt.**

**La page SOS-PGD du site Couperin de la Science ouverte permet de repérer les services de soutien locaux :** [**https://scienceouverte.couperin.org/sos-pgd/**](https://scienceouverte.couperin.org/sos-pgd/)​

------------------------------------------------------------------------

**Crédits :**
Réseau URFIST - Inist-CNRS : [PARCOURS INTERACTIF SUR LA GESTION DES DONNÉES DE LA RECHERCHE](https://doranum.fr/enjeux-benefices/parcours-interactif-sur-la-gestion-des-donnees-de-la-recherche/)
