---
title: "Fiche - Découvrir les différentes licences existantes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

------------------------------------------------------------------------

Pour rendre vos données réutilisables, il est important d'attribuer une licence et de la mentionner dans les métadonnées. Vous trouverez quelques recommandations et exemples pour guider votre réflexion.

------------------------------------------------------------------------

## Licences utilisables pour les données publiques

Dès lors que les données issues d'une activité de recherche financée au moins pour moitié par des dotations de l'Etat, des collectivités territoriales, des établissements publics, des subventions d'agences de financement nationales ou par des fonds de l'Union européenne ne sont pas protégées par un droit spécifique ou une réglementation particulière et qu'elles ont été rendues publiques par le chercheur, l'établissement ou l'organisme de recherche, **leur réutilisation est libre**.

<small>Source : [Article 30 de la Loi pour une république numérique](https://www.legifrance.gouv.fr/jorf/article_jo/JORFARTI000033202841)</small>

Plus largement, l'esprit de la réutilisation des données publiques (produites ou obtenues par les chercheurs dans le cadre de leur mission de service public) est d'être la plus libre possible, afin de multiplier les usages et de favoriser, ainsi, des usages nouveaux de ces données. En conséquence, quel que soit la licence, ses conditions ne peuvent apporter de restrictions à la réutilisation que pour des motifs d'intérêt général et de façon proportionnée.

La loi ne prévoit pas d'obligation pour les administrations de fixer une licence mais elles y sont fortement invitées à des fins pédagogiques, afin de faciliter aux réutilisateurs la compréhension de leurs droits et obligations.

<small>Source : [*Guide pratique de la publication en ligne et de la réutilisation des données publiques ("open data")*](https://www.cada.fr/sites/default/files/guide_pratique.pdf). CADA, CNIL et Etalab. 2019</small>

Afin d'éviter la prolifération des licences et d'assurer la circulation la plus fluide des données publiques et permettre leur croisement, les administrations ont un choix limité de licences utilisables pour la réutilisation à titre gratuit d'informations publiques, qu'il s'agisse de données ou de code source de logiciels. Elles figurent sur une liste établie par le [décret n° 2017-638 du 27 avril 2017 relatif aux licences de réutilisation à titre gratuit des informations publiques et aux modalités de leur homologation](https://www.legifrance.gouv.fr/eli/decret/2017/4/27/2017-638/jo/texte), notamment les licences ODBL et Licence ouverte d'Etalab pour les données.

<small>Source : [*Datapartage---Choisir une licence*](https://datapartage.inrae.fr/Partager-Publier/Choisir-une-licence)</small>

------------------------------------------------------------------------

## Licences recommandées

Il existe de nombreuses licences, modulables en fonction de vos besoins pour certaines, très spécifiques pour d'autres. Voici quelques exemples (liste non exhaustive) :

------------------------------------------------------------------------

**Licence ouverte (Etalab)** : cette licence ouverte, libre et gratuite est compatible avec la CC-BY 2.0, ce qui veut dire que la paternité des données devra être mentionnée en cas de réutilisation des données.

La « Licence Ouverte / Open License » présente les caractéristiques suivantes :

1.  Une grande liberté de réutilisation des informations :

    -   Une licence ouverte, libre et gratuite, qui apporte la sécurité juridique nécessaire aux producteurs et aux réutilisateurs des données publiques ;
    -   Une licence qui promeut la réutilisation la plus large en autorisant la reproduction, la redistribution, l'adaptation et l'exploitation commerciale des données ;
    -   Une licence qui s'inscrit dans un contexte international en étant compatible avec les standards des licences Open Data développées à l'étranger et notamment celles du gouvernement britannique (Open Government Licence) ainsi que les autres standards internationaux (ODC-BY, CC-BY 2.0). Il est tout à fait possible **d'attribuer à la fois une Licence ouverte et une licence CC-BY**.

2.  Une exigence forte de transparence de la donnée et de qualité des sources en rendant obligatoire la mention de la paternité.

3.  Une opportunité de mutualisation pour les autres données publiques en mettant en place un standard réutilisable par les collectivités territoriales qui souhaiteraient se lancer dans l'ouverture des données publiques.

<small>(Source : [Etalab](https://www.etalab.gouv.fr/licence-ouverte-open-licence/))</small>

------------------------------------------------------------------------

**Licence pour base de données** : la licence libre [Open Database License (ODbL)](https://fr.wikipedia.org/wiki/Open_Database_License) couvre spécifiquement les bases de données.

------------------------------------------------------------------------

**Licences CC - Creative Commons** - Il existe 6 licences Creative Commons combinant quatre éléments :

\- BY = attribution

\- NC = pas d'utilisation commerciale

\- SA = partage dans les mêmes conditions

\- ND = pas de modification

Voici les 6 licences Creative Commons et leurs icônes correspondantes (illustration ci-dessous) :

\- CC BY

\- CC BY-ND

\- CC BY-NC-ND

\- CC BY-NC

\- CC BY-NC-SA

\- CC BY-SA

La plus permissive est la CC BY et la plus restrictive est la CC BY-NC-ND (déconseillée).

En outre, la licence Creative Commons CC0 est équivalente à placer les données dans le domaine public (la réutilisation est entièrement libre).

------------------------------------------------------------------------

**Licences pour logiciels** : de façon schématique, il existe **trois degrés de copyleft** (*obligation de diffuser les œuvres modifiées sous la même licence que l'œuvre initiale*) pour les licences logiciels :

**Copyleft fort (licences GNU GPL)**
Ces licences, parfois dites « **diffusives** », imposent leurs termes à toute œuvre dérivée issue du logiciel. En particulier, **le respect des termes des licences à copyleft fort impose que les licences des autres modules soient libres, afin de garantir les libertés des usagers sur l'ensemble du logiciel**. L'obligation d'utiliser exactement la même licence ne s'applique qu'aux seules modifications internes au logiciel couvert.

**Copyleft faible (licences GNU LGPL)**
Ces licences permettent de **combiner le code qu'elles couvrent avec des modules tiers placés sous tous types de licences, y compris privatives**, à condition qu'il n'existe pas d'incompatibilité entre les licences.

**Non-copyleft (licences MIT, BSD, CeCILL-B, etc.)**
Ces licences, dites « **permissives** », n'ont **pas d'effet copyleft**. Elles permettent de modifier le code ou de l'intégrer dans un logiciel distribué sous tout autre type de licence, sans que l'usager puisse obtenir le code source de ce logiciel et exercer les droits initialement attachés à la licence libre. **Ce type de licence est à l'origine du fait que l'immense majorité des logiciels actuels -- libres ou non -- repose en partie sur du code initialement libre.**

"On constate qu'environ 60% des logiciels libres sont diffusés sous l'une des versions de la licence GNU GPL et 20% sous l'une des versions de la licence GNU LGPL."

<small> *Source : MOREAU, Patrick, MOULIN, Camille, PAPPALARDO, Jeremy et PELLEGRINI, François. Livret Bleu du Logiciel Libre : fondamentaux juridiques. 2016. Disponible à l'adresse : <https://cnll.fr/media/LivretBleu_Juridique-2eEdition_GT-LogicielLibre_Systematic_Nov2016_web.pdf>*</small>

------------------------------------------------------------------------

**Crédits :** Réseau URFIST - Inist-CNRS : [PARCOURS INTERACTIF SUR LA GESTION DES DONNÉES DE LA RECHERCHE](https://doranum.fr/enjeux-benefices/parcours-interactif-sur-la-gestion-des-donnees-de-la-recherche/)
